version: "3.8"
services:
  app:
    build: .
    ports:
      - "2345:3000" #set to whichever port you want
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist #
    restart: unless-stopped
